# 03 : NumPy

강의자료: `docs/course/03_NumPy.md`

ndarray 생성·인덱싱·기술통계·axis 방향 계산·원소별 연산·전치.
외부 데이터 없이 배열 리터럴만 쓴다.

In [1]:
import numpy as np
print(np.__version__)

2.5.3


## 1. 배열 생성

In [2]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))
print("shape:", arr.shape)   # (5,) — 원소 5개짜리 1차원

[1 2 3 4 5]
<class 'numpy.ndarray'>
shape: (5,)


In [3]:
# append는 원본을 바꾸지 않고 새 배열을 돌려준다
a = np.array([1, 2, 3])
b = np.append(a, [4, 5])
print("원본:", a)
print("결과:", b)

# 숫자와 문자열을 섞으면 전부 문자열로 승격된다 (dtype은 하나여야 하므로)
mixed = np.append(np.array([1, 2, 3]), ["넷"])
print(mixed, mixed.dtype)

원본: [1 2 3]
결과: [1 2 3 4 5]
['1' '2' '3' '넷'] <U21


## 2. 차원

In [4]:
d1 = np.array([1, 2, 3])
d2 = np.array([[1, 2, 3], [4, 5, 6]])
d3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for name, a in [("1차원", d1), ("2차원", d2), ("3차원", d3)]:
    print(f"{name}  ndim={a.ndim}  shape={a.shape}  크기={a.size}")

1차원  ndim=1  shape=(3,)  크기=3
2차원  ndim=2  shape=(2, 3)  크기=6
3차원  ndim=3  shape=(2, 2, 2)  크기=8


## 3. 인덱싱

In [5]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[0], arr[2], arr[-1])

arr[0] = 99          # 값 수정
print(arr)

m = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("2행 3열:", m[1, 2])    # 행, 열 (0부터)
print("2행 전체:", m[1])
print("3열 전체:", m[:, 2])

10 30 50
[99 20 30 40 50]
2행 3열: 6
2행 전체: [4 5 6]
3열 전체: [3 6 9]


## 4. 슬라이싱

In [6]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

print(arr[2:5])      # 2 이상 5 미만
print(arr[:3])       # 처음부터 3 미만
print(arr[7:])       # 7부터 끝까지
print(arr[-3:])      # 뒤에서 3개
print(arr[::2])      # 두 칸씩 건너뛰기

[2 3 4]
[0 1 2]
[7 8 9]
[7 8 9]
[0 2 4 6 8]


## 5. arange

In [7]:
print(np.arange(10))
print(np.arange(2, 10))
print(np.arange(0, 20, 5))
print(np.arange(0, 1, 0.25))   # 실수 간격도 된다

[0 1 2 3 4 5 6 7 8 9]
[2 3 4 5 6 7 8 9]
[ 0  5 10 15]
[0.   0.25 0.5  0.75]


## 6. 기술통계

In [8]:
data = np.array([23, 45, 12, 67, 34, 89, 21, 56])

print(f"개수   {len(data)}")
print(f"합계   {data.sum()}")
print(f"곱     {data.prod()}")
print(f"최소   {data.min()}  (위치 {data.argmin()})")
print(f"최대   {data.max()}  (위치 {data.argmax()})")
print(f"평균   {data.mean():.2f}")
print(f"표준편차 {data.std():.2f}")

for q in (25, 50, 75):
    print(f"{q}% 분위수 {np.percentile(data, q):.2f}")

개수   8
합계   347
곱     2961233432640
최소   12  (위치 2)
최대   89  (위치 5)
평균   43.38
표준편차 24.47
25% 분위수 22.50
50% 분위수 39.50
75% 분위수 58.75


## 7. axis — 어느 방향으로 계산할 것인가

`axis=0`은 행을 따라 내려가며 **열별로**, `axis=1`은 열을 따라 가로지르며 **행별로** 계산한다.
헷갈리면 "사라지는 축"을 생각하면 된다. `axis=0`이면 행 축이 사라져 열만 남는다.

In [9]:
m = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

print("전체 합계:", m.sum())
print("열별 합계 (axis=0):", m.sum(axis=0))   # 1+4+7, 2+5+8, 3+6+9
print("행별 합계 (axis=1):", m.sum(axis=1))   # 1+2+3, 4+5+6, 7+8+9
print("열별 평균 (axis=0):", m.mean(axis=0))

전체 합계: 45
열별 합계 (axis=0): [12 15 18]
행별 합계 (axis=1): [ 6 15 24]
열별 평균 (axis=0): [4. 5. 6.]


## 8. 원소별 연산

In [10]:
a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])

print("덧셈:", a + b)
print("뺄셈:", b - a)
print("곱셈:", a * b)          # 행렬곱이 아니라 원소별 곱
print("나눗셈:", b / a)
print("스칼라 곱:", a * 10)     # 브로드캐스팅

print("제곱근:", np.sqrt(np.array([1, 4, 9, 16])))
print("자연로그:", np.log(np.array([1, np.e, np.e ** 2])))

덧셈: [11 22 33 44]
뺄셈: [ 9 18 27 36]
곱셈: [ 10  40  90 160]
나눗셈: [10. 10. 10. 10.]
스칼라 곱: [10 20 30 40]
제곱근: [1. 2. 3. 4.]
자연로그: [0. 1. 2.]


## 9. 전치

In [11]:
m = np.array([[1, 2, 3], [4, 5, 6]])
print("원본", m.shape)
print(m)
print("\n전치", m.T.shape)
print(m.T)

원본 (2, 3)
[[1 2 3]
 [4 5 6]]

전치 (3, 2)
[[1 4]
 [2 5]
 [3 6]]


## 과제 1 — 미세먼지 배열 분석

3개 지점 x 4개 시간대의 PM2.5 측정값.

In [12]:
pm25 = np.array([[35, 42, 38, 45],    # 지점 1
                 [28, 31, 29, 33],    # 지점 2
                 [52, 58, 61, 55]])   # 지점 3

# 1) 차원과 모양
print(f"ndim={pm25.ndim}  shape={pm25.shape}")

# 2) 두 번째 지점
print("\n두 번째 지점:", pm25[1])

# 3) 지점별 평균은 행 방향(axis=1), 시간대별 평균은 열 방향(axis=0)
print("\n지점별 평균:", pm25.mean(axis=1).round(2))
print("시간대별 평균:", pm25.mean(axis=0).round(2))

# 4) 전체 최대값과 위치
#    argmax는 1차원으로 편 기준의 위치를 주므로 unravel_index로 (행, 열)로 되돌린다
flat = pm25.argmax()
row, col = np.unravel_index(flat, pm25.shape)
print(f"\n최대값 {pm25.max()} — 지점 {row + 1}, 시간대 {col + 1}")

# 5) 전치
print(f"\n전치 전 {pm25.shape} → 전치 후 {pm25.T.shape}")
print(pm25.T)

ndim=2  shape=(3, 4)

두 번째 지점: [28 31 29 33]

지점별 평균: [40.   30.25 56.5 ]
시간대별 평균: [38.33 43.67 42.67 44.33]

최대값 61 — 지점 3, 시간대 3

전치 전 (3, 4) → 전치 후 (4, 3)
[[35 28 52]
 [42 31 58]
 [38 29 61]
 [45 33 55]]
